### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by Perthys**

### CODE REVIEW

**Comment by TheGreatSageEqualToHeaven** [comment]
Consider writing a more descriptive pr, follow this format.

**What does this pr do**
**What steps have you done to fix this**
**Have you considered other solutions**

**Review by memcorrupt — CHANGES_REQUESTED** [review]
Unfortunately, our legal team has not approved this change.

**Review by TheGreatSageEqualToHeaven — CHANGES_REQUESTED** [review]
Consider keeping `- Perth` and adding `- Bmcq`

**Comment by Perthys** [comment]
I concur this change

**Pull request closed without merging**
